"""Build the release ledger from files Git would include.

The manifest and checksum files are deliberately excluded from their own hash
inputs so rerunning this script is deterministic and does not recurse.
"""
from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent
EXCLUDE = {"MANIFEST.md", "SHA256SUMS.txt"}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def intended_public_files() -> list[Path]:
    cmd = [
        "git", "-c", f"safe.directory={ROOT}", "-C", str(ROOT),
        "ls-files", "--cached", "--others", "--exclude-standard",
    ]
    rels = subprocess.check_output(cmd, text=True, encoding="utf-8").splitlines()
    return sorted(
        (ROOT / rel for rel in rels if rel.replace("\\", "/") not in EXCLUDE),
        key=lambda p: p.relative_to(ROOT).as_posix().lower(),
    )


def main() -> None:
    rows = []
    for path in intended_public_files():
        if path.is_file():
            rows.append((sha256(path), path.stat().st_size, path.relative_to(ROOT).as_posix()))

    checksum = "".join(f"{digest}  {rel}\n" for digest, _, rel in rows)
    with (ROOT / "SHA256SUMS.txt").open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(checksum)

    lines = [
        "# Public release manifest", "",
        "This ledger was generated by `build_release_manifest.py` from the exact",
        "set of tracked or unignored files that Git would include. `MANIFEST.md` and",
        "`SHA256SUMS.txt` are excluded from their own hash input. Ignored local smoke",
        "outputs, public-data working files, restricted inputs, and `.git/` are absent.", "",
        f"Intended public files hashed: **{len(rows)}**.", "",
        "| SHA-256 | Bytes | Relative path |", "|---|---:|---|",
    ]
    lines.extend(f"| `{digest}` | {size} | `{rel}` |" for digest, size, rel in rows)
    lines.extend([
        "", "No institutional patient-level inputs or raw images are intentionally included.",
        "No local executable path, user directory, or institutional filesystem path",
        "is retained in the public files.", "",
    ])
    with (ROOT / "MANIFEST.md").open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"Wrote {len(rows)} hashes")


if __name__ == "__main__":
    main()
